<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleHybridWithPkce</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="ZinfoFramework.IdentityModel.OidcClient" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constants\Constants.csproj" />
  </ItemGroup>
</Project>
